import {type Metadata} from 'next'
import {ClerkProvider,} from '@clerk/nextjs'
import {Geist, Geist_Mono} from 'next/font/google'
import './globals.css'
import {ThemeProvider} from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import {Toaster} from "react-hot-toast";

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Clerk Next.js Quickstart',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <div className="flex flex-col min-h-screen">
                    <Navbar/>
                    <main className="flex-1 py-8">
                        {/*  container to center the content  */}
                        <div className="max-w-7xl mx-auto px-4 h-full">
                            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 h-full">
                                <div className="hidden lg:block lg:col-span-3">
                                    <Sidebar/>
                                </div>
                                <div className="lg:col-span-9">
                                    {children}
                                </div>
                            </div>
                        </div>
                    </main>
                    <Footer/>
                </div>
                <Toaster />
            </ThemeProvider>
            </body>
            </html>
        </ClerkProvider>
    )
}